// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelf->CLK));
    bufp->chgBit(oldp+1,(vlSelf->BTNL));
    bufp->chgBit(oldp+2,(vlSelf->BTNC));
    bufp->chgSData(oldp+3,(vlSelf->SWITCHES),16);
    bufp->chgSData(oldp+4,(vlSelf->LEDS),16);
    bufp->chgCData(oldp+5,(vlSelf->CATHODES),8);
    bufp->chgCData(oldp+6,(vlSelf->ANODES),4);
    bufp->chgBit(oldp+7,(vlSelf->OTTER_Wrapper__DOT__CLK));
    bufp->chgBit(oldp+8,(vlSelf->OTTER_Wrapper__DOT__BTNL));
    bufp->chgBit(oldp+9,(vlSelf->OTTER_Wrapper__DOT__BTNC));
    bufp->chgSData(oldp+10,(vlSelf->OTTER_Wrapper__DOT__SWITCHES),16);
    bufp->chgSData(oldp+11,(vlSelf->OTTER_Wrapper__DOT__LEDS),16);
    bufp->chgCData(oldp+12,(vlSelf->OTTER_Wrapper__DOT__CATHODES),8);
    bufp->chgCData(oldp+13,(vlSelf->OTTER_Wrapper__DOT__ANODES),4);
    bufp->chgBit(oldp+14,(vlSelf->OTTER_Wrapper__DOT__clk_50));
    bufp->chgIData(oldp+15,(vlSelf->OTTER_Wrapper__DOT__IOBUS_out),32);
    bufp->chgIData(oldp+16,(vlSelf->OTTER_Wrapper__DOT__IOBUS_in),32);
    bufp->chgIData(oldp+17,(vlSelf->OTTER_Wrapper__DOT__IOBUS_addr),32);
    bufp->chgSData(oldp+18,(vlSelf->OTTER_Wrapper__DOT__r_lcdinstr),10);
    bufp->chgBit(oldp+19,(vlSelf->OTTER_Wrapper__DOT__r_lcd_ready));
    bufp->chgIData(oldp+20,(vlSelf->OTTER_Wrapper__DOT__r_random),32);
    bufp->chgBit(oldp+21,(vlSelf->OTTER_Wrapper__DOT__s_reset));
    bufp->chgBit(oldp+22,(vlSelf->OTTER_Wrapper__DOT__IOBUS_wr));
    bufp->chgBit(oldp+23,(vlSelf->OTTER_Wrapper__DOT__s_INTR));
    bufp->chgBit(oldp+24,(vlSelf->OTTER_Wrapper__DOT__r_vga_we));
    bufp->chgSData(oldp+25,(vlSelf->OTTER_Wrapper__DOT__r_vga_wa),13);
    bufp->chgCData(oldp+26,(vlSelf->OTTER_Wrapper__DOT__r_vga_wd),8);
    bufp->chgCData(oldp+27,(vlSelf->OTTER_Wrapper__DOT__r_vga_rd),8);
    bufp->chgSData(oldp+28,(vlSelf->OTTER_Wrapper__DOT__r_SSEG),16);
    bufp->chgBit(oldp+29,(vlSelf->OTTER_Wrapper__DOT__BTN_INTR));
    bufp->chgBit(oldp+30,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RST));
    bufp->chgBit(oldp+31,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__INTR));
    bufp->chgBit(oldp+32,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CLK));
    bufp->chgIData(oldp+33,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_IN),32);
    bufp->chgBit(oldp+34,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_WR));
    bufp->chgIData(oldp+35,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_OUT),32);
    bufp->chgIData(oldp+36,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_ADDR),32);
    bufp->chgIData(oldp+37,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pc_bus),32);
    bufp->chgIData(oldp+38,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__npc_bus),32);
    bufp->chgIData(oldp+39,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rs1_bus),32);
    bufp->chgIData(oldp+40,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rs2_bus),32);
    bufp->chgIData(oldp+41,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_res_bus),32);
    bufp->chgIData(oldp+42,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__instr_bus),32);
    bufp->chgIData(oldp+43,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__itype_bus),32);
    bufp->chgIData(oldp+44,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__utype_bus),32);
    bufp->chgIData(oldp+45,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__stype_bus),32);
    bufp->chgIData(oldp+46,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jtype_bus),32);
    bufp->chgIData(oldp+47,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__btype_bus),32);
    bufp->chgIData(oldp+48,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__csr_RD),32);
    bufp->chgIData(oldp+49,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MTVEC),32);
    bufp->chgIData(oldp+50,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEPC),32);
    bufp->chgIData(oldp+51,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MSTATUS),32);
    bufp->chgBit(oldp+52,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__mret_exec));
    bufp->chgBit(oldp+53,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__int_taken));
    bufp->chgBit(oldp+54,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__csr_WE));
    bufp->chgIData(oldp+55,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__mem_data),32);
    bufp->chgIData(oldp+56,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jalr_baddr),32);
    bufp->chgIData(oldp+57,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__branch_baddr),32);
    bufp->chgIData(oldp+58,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jal_baddr),32);
    bufp->chgBit(oldp+59,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_eq));
    bufp->chgBit(oldp+60,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_lt));
    bufp->chgBit(oldp+61,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_ltu));
    bufp->chgIData(oldp+62,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rfwrmux_to_rf),32);
    bufp->chgIData(oldp+63,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__srcAmux_to_alu),32);
    bufp->chgIData(oldp+64,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__srcBmux_to_alu),32);
    bufp->chgIData(oldp+65,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pcmux_to_pc),32);
    bufp->chgBit(oldp+66,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PCWrite));
    bufp->chgBit(oldp+67,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__regWrite));
    bufp->chgBit(oldp+68,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memWE2));
    bufp->chgBit(oldp+69,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memRDEN1));
    bufp->chgBit(oldp+70,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memRDEN2));
    bufp->chgBit(oldp+71,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__reset));
    bufp->chgCData(oldp+72,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_fun),4);
    bufp->chgCData(oldp+73,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_srcA),2);
    bufp->chgCData(oldp+74,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_srcB),3);
    bufp->chgCData(oldp+75,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pcSource),3);
    bufp->chgCData(oldp+76,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rf_wr_sel),2);
    bufp->chgIData(oldp+77,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__srcA),32);
    bufp->chgIData(oldp+78,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__srcB),32);
    bufp->chgCData(oldp+79,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__ALU_FUN),4);
    bufp->chgIData(oldp+80,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__RESULT),32);
    bufp->chgIData(oldp+81,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__A),32);
    bufp->chgIData(oldp+82,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__B),32);
    bufp->chgIData(oldp+83,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__C),32);
    bufp->chgIData(oldp+84,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__D),32);
    bufp->chgCData(oldp+85,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__sel),2);
    bufp->chgIData(oldp+86,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__O),32);
    bufp->chgIData(oldp+87,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__A),32);
    bufp->chgIData(oldp+88,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__B),32);
    bufp->chgIData(oldp+89,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__C),32);
    bufp->chgIData(oldp+90,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__D),32);
    bufp->chgIData(oldp+91,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__E),32);
    bufp->chgIData(oldp+92,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__F),32);
    bufp->chgCData(oldp+93,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__sel),3);
    bufp->chgIData(oldp+94,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__O),32);
    bufp->chgIData(oldp+95,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__J_TYPE),32);
    bufp->chgIData(oldp+96,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__B_TYPE),32);
    bufp->chgIData(oldp+97,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__PC),32);
    bufp->chgIData(oldp+98,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__I_TYPE),32);
    bufp->chgIData(oldp+99,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__RS1),32);
    bufp->chgIData(oldp+100,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__JAL),32);
    bufp->chgIData(oldp+101,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__BRANCH),32);
    bufp->chgIData(oldp+102,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__JALR),32);
    bufp->chgIData(oldp+103,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__RS1),32);
    bufp->chgIData(oldp+104,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__RS2),32);
    bufp->chgBit(oldp+105,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_EQ));
    bufp->chgBit(oldp+106,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_LT));
    bufp->chgBit(oldp+107,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_LTU));
    bufp->chgBit(oldp+108,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__clk));
    bufp->chgBit(oldp+109,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__RST));
    bufp->chgBit(oldp+110,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__mret_exec));
    bufp->chgBit(oldp+111,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__INT_TAKEN));
    bufp->chgSData(oldp+112,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__ADDR),12);
    bufp->chgBit(oldp+113,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__WR_EN));
    bufp->chgIData(oldp+114,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__PC),32);
    bufp->chgIData(oldp+115,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__WD),32);
    bufp->chgIData(oldp+116,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__RD),32);
    bufp->chgIData(oldp+117,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MSTATUS),32);
    bufp->chgIData(oldp+118,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MEPC),32);
    bufp->chgIData(oldp+119,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MTVEC),32);
    bufp->chgCData(oldp+120,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__opcode),7);
    bufp->chgCData(oldp+121,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__funct3),3);
    bufp->chgBit(oldp+122,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__funct7));
    bufp->chgBit(oldp+123,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_eq));
    bufp->chgBit(oldp+124,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_lt));
    bufp->chgBit(oldp+125,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_ltu));
    bufp->chgBit(oldp+126,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__int_taken));
    bufp->chgCData(oldp+127,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_fun),4);
    bufp->chgCData(oldp+128,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_srcA),2);
    bufp->chgCData(oldp+129,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_srcB),3);
    bufp->chgCData(oldp+130,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__pcSource),3);
    bufp->chgCData(oldp+131,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__rf_wr_sel),2);
    bufp->chgBit(oldp+132,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__clk));
    bufp->chgBit(oldp+133,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__RST));
    bufp->chgBit(oldp+134,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__INTR));
    bufp->chgCData(oldp+135,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__opcode),7);
    bufp->chgCData(oldp+136,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__funct3),3);
    bufp->chgBit(oldp+137,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__PCWrite));
    bufp->chgBit(oldp+138,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__regWrite));
    bufp->chgBit(oldp+139,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memWE2));
    bufp->chgBit(oldp+140,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memRDEN1));
    bufp->chgBit(oldp+141,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memRDEN2));
    bufp->chgBit(oldp+142,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__reset));
    bufp->chgBit(oldp+143,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__csr_WE));
    bufp->chgBit(oldp+144,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__int_taken));
    bufp->chgBit(oldp+145,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__mret_exec));
    bufp->chgIData(oldp+146,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__NS),32);
    bufp->chgIData(oldp+147,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__PS),32);
    bufp->chgIData(oldp+148,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__INSTRUCT),32);
    bufp->chgIData(oldp+149,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__U_TYPE),32);
    bufp->chgIData(oldp+150,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__I_TYPE),32);
    bufp->chgIData(oldp+151,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__S_TYPE),32);
    bufp->chgIData(oldp+152,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__J_TYPE),32);
    bufp->chgIData(oldp+153,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__B_TYPE),32);
    bufp->chgBit(oldp+154,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_CLK));
    bufp->chgBit(oldp+155,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_RDEN1));
    bufp->chgBit(oldp+156,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_RDEN2));
    bufp->chgBit(oldp+157,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_WE2));
    bufp->chgSData(oldp+158,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_ADDR1),14);
    bufp->chgIData(oldp+159,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_ADDR2),32);
    bufp->chgIData(oldp+160,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DIN2),32);
    bufp->chgCData(oldp+161,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_SIZE),2);
    bufp->chgBit(oldp+162,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_SIGN));
    bufp->chgIData(oldp+163,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__IO_IN),32);
    bufp->chgBit(oldp+164,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__IO_WR));
    bufp->chgIData(oldp+165,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DOUT1),32);
    bufp->chgIData(oldp+166,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DOUT2),32);
    bufp->chgSData(oldp+167,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__wordAddr2),14);
    bufp->chgIData(oldp+168,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__memReadWord),32);
    bufp->chgIData(oldp+169,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__ioBuffer),32);
    bufp->chgIData(oldp+170,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__memReadSized),32);
    bufp->chgCData(oldp+171,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__byteOffset),2);
    bufp->chgBit(oldp+172,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__weAddrValid));
    bufp->chgBit(oldp+173,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_WRITE));
    bufp->chgBit(oldp+174,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_RST));
    bufp->chgIData(oldp+175,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_DIN),32);
    bufp->chgBit(oldp+176,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__CLK));
    bufp->chgIData(oldp+177,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_COUNT),32);
    bufp->chgIData(oldp+178,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__A),32);
    bufp->chgIData(oldp+179,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__B),32);
    bufp->chgIData(oldp+180,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__C),32);
    bufp->chgIData(oldp+181,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__D),32);
    bufp->chgIData(oldp+182,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__E),32);
    bufp->chgIData(oldp+183,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__F),32);
    bufp->chgCData(oldp+184,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__sel),3);
    bufp->chgIData(oldp+185,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__O),32);
    bufp->chgCData(oldp+186,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_ADR1),5);
    bufp->chgCData(oldp+187,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_ADR2),5);
    bufp->chgCData(oldp+188,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_WA),5);
    bufp->chgIData(oldp+189,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_WD),32);
    bufp->chgBit(oldp+190,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_EN));
    bufp->chgBit(oldp+191,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__CLK));
    bufp->chgIData(oldp+192,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_RS1),32);
    bufp->chgIData(oldp+193,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_RS2),32);
    bufp->chgIData(oldp+194,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[0]),32);
    bufp->chgIData(oldp+195,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[1]),32);
    bufp->chgIData(oldp+196,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[2]),32);
    bufp->chgIData(oldp+197,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[3]),32);
    bufp->chgIData(oldp+198,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[4]),32);
    bufp->chgIData(oldp+199,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[5]),32);
    bufp->chgIData(oldp+200,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[6]),32);
    bufp->chgIData(oldp+201,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[7]),32);
    bufp->chgIData(oldp+202,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[8]),32);
    bufp->chgIData(oldp+203,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[9]),32);
    bufp->chgIData(oldp+204,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[10]),32);
    bufp->chgIData(oldp+205,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[11]),32);
    bufp->chgIData(oldp+206,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[12]),32);
    bufp->chgIData(oldp+207,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[13]),32);
    bufp->chgIData(oldp+208,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[14]),32);
    bufp->chgIData(oldp+209,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[15]),32);
    bufp->chgIData(oldp+210,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[16]),32);
    bufp->chgIData(oldp+211,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[17]),32);
    bufp->chgIData(oldp+212,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[18]),32);
    bufp->chgIData(oldp+213,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[19]),32);
    bufp->chgIData(oldp+214,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[20]),32);
    bufp->chgIData(oldp+215,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[21]),32);
    bufp->chgIData(oldp+216,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[22]),32);
    bufp->chgIData(oldp+217,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[23]),32);
    bufp->chgIData(oldp+218,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[24]),32);
    bufp->chgIData(oldp+219,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[25]),32);
    bufp->chgIData(oldp+220,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[26]),32);
    bufp->chgIData(oldp+221,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[27]),32);
    bufp->chgIData(oldp+222,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[28]),32);
    bufp->chgIData(oldp+223,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[29]),32);
    bufp->chgIData(oldp+224,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[30]),32);
    bufp->chgIData(oldp+225,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[31]),32);
    bufp->chgIData(oldp+226,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__A),32);
    bufp->chgIData(oldp+227,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__B),32);
    bufp->chgIData(oldp+228,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__C),32);
    bufp->chgIData(oldp+229,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__D),32);
    bufp->chgCData(oldp+230,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__sel),2);
    bufp->chgIData(oldp+231,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__O),32);
    bufp->chgBit(oldp+232,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__CLK));
    bufp->chgBit(oldp+233,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__BTN));
    bufp->chgBit(oldp+234,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__DB_BTN));
    bufp->chgCData(oldp+235,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_LOW_GOING_HIGH_CLOCKS),8);
    bufp->chgCData(oldp+236,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_HIGH_GOING_LOW_CLOCKS),8);
    bufp->chgCData(oldp+237,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_ONE_SHOT_CLOCKS),8);
    bufp->chgIData(oldp+238,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__NS),32);
    bufp->chgIData(oldp+239,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__PS),32);
    bufp->chgCData(oldp+240,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_db_count),8);
    bufp->chgBit(oldp+241,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_count_rst));
    bufp->chgBit(oldp+242,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_count_inc));
    bufp->chgBit(oldp+243,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CLK));
    bufp->chgBit(oldp+244,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__MODE));
    bufp->chgSData(oldp+245,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__DATA_IN),16);
    bufp->chgCData(oldp+246,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CATHODES),8);
    bufp->chgCData(oldp+247,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__ANODES),4);
    bufp->chgSData(oldp+248,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCD_Val),16);
    bufp->chgSData(oldp+249,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__Hex_Val),16);
    bufp->chgSData(oldp+250,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__HEX),16);
    bufp->chgCData(oldp+251,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__THOUSANDS),4);
    bufp->chgCData(oldp+252,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__HUNDREDS),4);
    bufp->chgCData(oldp+253,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__TENS),4);
    bufp->chgCData(oldp+254,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__ONES),4);
    bufp->chgIData(oldp+255,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__i),32);
    bufp->chgBit(oldp+256,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__CLK));
    bufp->chgSData(oldp+257,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__HEX),16);
    bufp->chgCData(oldp+258,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__CATHODES),8);
    bufp->chgCData(oldp+259,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__ANODES),4);
    bufp->chgBit(oldp+260,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__s_clk_500));
    bufp->chgCData(oldp+261,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__r_disp_digit),2);
    bufp->chgIData(oldp+262,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__clk_div_counter),20);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
