// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+2,0,"BTNL",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+3,0,"BTNC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+4,0,"SWITCHES",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+5,0,"LEDS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+6,0,"CATHODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+7,0,"ANODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->pushPrefix("OTTER_Wrapper", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+8,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+9,0,"BTNL",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+10,0,"BTNC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+11,0,"SWITCHES",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+12,0,"LEDS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+13,0,"CATHODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+14,0,"ANODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+264,0,"SWITCHES_AD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+265,0,"LEDS_AD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+266,0,"SSEG_AD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::PARAMETER, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+15,0,"clk_50",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+16,0,"IOBUS_out",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+17,0,"IOBUS_in",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+18,0,"IOBUS_addr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+19,0,"r_lcdinstr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 9,0);
    tracep->declBit(c+20,0,"r_lcd_ready",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+21,0,"r_random",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+22,0,"s_reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+23,0,"IOBUS_wr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+24,0,"s_INTR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+25,0,"r_vga_we",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+26,0,"r_vga_wa",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 12,0);
    tracep->declBus(c+27,0,"r_vga_wd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+28,0,"r_vga_rd",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+29,0,"r_SSEG",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBit(c+30,0,"BTN_INTR",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->pushPrefix("CPU", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+31,0,"RST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+32,0,"INTR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+33,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+34,0,"IOBUS_IN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+35,0,"IOBUS_WR",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+36,0,"IOBUS_OUT",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+37,0,"IOBUS_ADDR",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+38,0,"pc_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+39,0,"npc_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+40,0,"rs1_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+41,0,"rs2_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+42,0,"alu_res_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+43,0,"instr_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+44,0,"itype_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+45,0,"utype_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+46,0,"stype_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+47,0,"jtype_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+48,0,"btype_bus",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+49,0,"csr_RD",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+50,0,"MTVEC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+51,0,"MEPC",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+52,0,"MSTATUS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+53,0,"mret_exec",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+54,0,"int_taken",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+55,0,"csr_WE",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+56,0,"mem_data",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+57,0,"jalr_baddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+58,0,"branch_baddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+59,0,"jal_baddr",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+60,0,"bcond_to_cu_eq",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+61,0,"bcond_to_cu_lt",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+62,0,"bcond_to_cu_ltu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+63,0,"rfwrmux_to_rf",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+64,0,"srcAmux_to_alu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+65,0,"srcBmux_to_alu",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+66,0,"pcmux_to_pc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+67,0,"PCWrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+68,0,"regWrite",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+69,0,"memWE2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+70,0,"memRDEN1",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+71,0,"memRDEN2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+72,0,"reset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+73,0,"alu_fun",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+74,0,"alu_srcA",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+75,0,"alu_srcB",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+76,0,"pcSource",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+77,0,"rf_wr_sel",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->pushPrefix("ALU0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+78,0,"srcA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+79,0,"srcB",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+80,0,"ALU_FUN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+81,0,"RESULT",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("ALU_SRCA_MUX", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+82,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+83,0,"B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+84,0,"C",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+85,0,"D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+86,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+87,0,"O",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("ALU_SRCB_MUX", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+88,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+89,0,"B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+90,0,"C",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+91,0,"D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+92,0,"E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+93,0,"F",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+94,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+95,0,"O",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("BADDR_GEN0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+96,0,"J_TYPE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+97,0,"B_TYPE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+98,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+99,0,"I_TYPE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+100,0,"RS1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+101,0,"JAL",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+102,0,"BRANCH",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+103,0,"JALR",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("BCOND_GEN0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+104,0,"RS1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+105,0,"RS2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+106,0,"BR_EQ",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+107,0,"BR_LT",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+108,0,"BR_LTU",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("CSR0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+109,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+110,0,"RST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+111,0,"mret_exec",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+112,0,"INT_TAKEN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+113,0,"ADDR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 11,0);
    tracep->declBit(c+114,0,"WR_EN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+115,0,"PC",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+116,0,"WD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+117,0,"RD",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+118,0,"MSTATUS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+119,0,"MEPC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+120,0,"MTVEC",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("CU_DCDR0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+121,0,"opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+122,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+123,0,"funct7",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+124,0,"br_eq",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+125,0,"br_lt",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+126,0,"br_ltu",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+127,0,"int_taken",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+128,0,"alu_fun",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+129,0,"alu_srcA",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+130,0,"alu_srcB",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+131,0,"pcSource",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+132,0,"rf_wr_sel",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->popPrefix();
    tracep->pushPrefix("CU_FSM0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+133,0,"clk",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+134,0,"RST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+135,0,"INTR",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+136,0,"opcode",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 6,0);
    tracep->declBus(c+137,0,"funct3",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBit(c+138,0,"PCWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+139,0,"regWrite",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+140,0,"memWE2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+141,0,"memRDEN1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+142,0,"memRDEN2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+143,0,"reset",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+144,0,"csr_WE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+145,0,"int_taken",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+146,0,"mret_exec",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+147,0,"NS",1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+148,0,"PS",1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("IMMED_GEN0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+149,0,"INSTRUCT",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+150,0,"U_TYPE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+151,0,"I_TYPE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+152,0,"S_TYPE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+153,0,"J_TYPE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+154,0,"B_TYPE",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("MEM0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+155,0,"MEM_CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+156,0,"MEM_RDEN1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+157,0,"MEM_RDEN2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+158,0,"MEM_WE2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+159,0,"MEM_ADDR1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+160,0,"MEM_ADDR2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+161,0,"MEM_DIN2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+162,0,"MEM_SIZE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+163,0,"MEM_SIGN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+164,0,"IO_IN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+165,0,"IO_WR",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+166,0,"MEM_DOUT1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+167,0,"MEM_DOUT2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+168,0,"wordAddr2",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 13,0);
    tracep->declBus(c+169,0,"memReadWord",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+170,0,"ioBuffer",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+171,0,"memReadSized",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+172,0,"byteOffset",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBit(c+173,0,"weAddrValid",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("PC0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+174,0,"PC_WRITE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+175,0,"PC_RST",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+176,0,"PC_DIN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+177,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+178,0,"PC_COUNT",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("PC_MUX", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+179,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+180,0,"B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+181,0,"C",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+182,0,"D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+183,0,"E",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+184,0,"F",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+185,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 2,0);
    tracep->declBus(c+186,0,"O",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("RF0", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+187,0,"RF_ADR1",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+188,0,"RF_ADR2",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+189,0,"RF_WA",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 4,0);
    tracep->declBus(c+190,0,"RF_WD",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBit(c+191,0,"RF_EN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+192,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+193,0,"RF_RS1",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+194,0,"RF_RS2",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->pushPrefix("ram", VerilatedTracePrefixType::ARRAY_UNPACKED);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+195+i*1,0,"",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, true,(i+0), 31,0);
    }
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("RF_WR_MUX", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+227,0,"A",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+228,0,"B",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+229,0,"C",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+230,0,"D",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->declBus(c+231,0,"sel",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+232,0,"O",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 31,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->pushPrefix("DEBOUCE", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+233,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+234,0,"BTN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+235,0,"DB_BTN",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+236,0,"c_LOW_GOING_HIGH_CLOCKS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+237,0,"c_HIGH_GOING_LOW_CLOCKS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+238,0,"c_ONE_SHOT_CLOCKS",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+239,0,"NS",2, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+240,0,"PS",2, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->declBus(c+241,0,"s_db_count",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBit(c+242,0,"s_count_rst",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+243,0,"s_count_inc",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->popPrefix();
    tracep->pushPrefix("SSG_DISP", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+244,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBit(c+245,0,"MODE",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+246,0,"DATA_IN",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+247,0,"CATHODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+248,0,"ANODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+249,0,"BCD_Val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+250,0,"Hex_Val",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->pushPrefix("BCDMod", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBus(c+251,0,"HEX",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+252,0,"THOUSANDS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+253,0,"HUNDREDS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+254,0,"TENS",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+255,0,"ONES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBus(c+256,0,"i",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::INT, false,-1, 31,0);
    tracep->popPrefix();
    tracep->pushPrefix("CathMod", VerilatedTracePrefixType::SCOPE_MODULE);
    tracep->declBit(c+257,0,"CLK",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+258,0,"HEX",-1, VerilatedTraceSigDirection::INPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 15,0);
    tracep->declBus(c+259,0,"CATHODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 7,0);
    tracep->declBus(c+260,0,"ANODES",-1, VerilatedTraceSigDirection::OUTPUT, VerilatedTraceSigKind::WIRE, VerilatedTraceSigType::LOGIC, false,-1, 3,0);
    tracep->declBit(c+261,0,"s_clk_500",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1);
    tracep->declBus(c+262,0,"r_disp_digit",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 1,0);
    tracep->declBus(c+263,0,"clk_div_counter",-1, VerilatedTraceSigDirection::NONE, VerilatedTraceSigKind::VAR, VerilatedTraceSigType::LOGIC, false,-1, 19,0);
    tracep->popPrefix();
    tracep->popPrefix();
    tracep->popPrefix();
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp);
VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addConstCb(&Vtop___024root__trace_const_0, 0U, vlSelf);
    tracep->addFullCb(&Vtop___024root__trace_full_0, 0U, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_0, 0U, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_const_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_const_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_const_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_const_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+264,(0x11000000U),32);
    bufp->fullIData(oldp+265,(0x11000020U),32);
    bufp->fullIData(oldp+266,(0x11000040U),32);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_0_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_0_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->CLK));
    bufp->fullBit(oldp+2,(vlSelf->BTNL));
    bufp->fullBit(oldp+3,(vlSelf->BTNC));
    bufp->fullSData(oldp+4,(vlSelf->SWITCHES),16);
    bufp->fullSData(oldp+5,(vlSelf->LEDS),16);
    bufp->fullCData(oldp+6,(vlSelf->CATHODES),8);
    bufp->fullCData(oldp+7,(vlSelf->ANODES),4);
    bufp->fullBit(oldp+8,(vlSelf->OTTER_Wrapper__DOT__CLK));
    bufp->fullBit(oldp+9,(vlSelf->OTTER_Wrapper__DOT__BTNL));
    bufp->fullBit(oldp+10,(vlSelf->OTTER_Wrapper__DOT__BTNC));
    bufp->fullSData(oldp+11,(vlSelf->OTTER_Wrapper__DOT__SWITCHES),16);
    bufp->fullSData(oldp+12,(vlSelf->OTTER_Wrapper__DOT__LEDS),16);
    bufp->fullCData(oldp+13,(vlSelf->OTTER_Wrapper__DOT__CATHODES),8);
    bufp->fullCData(oldp+14,(vlSelf->OTTER_Wrapper__DOT__ANODES),4);
    bufp->fullBit(oldp+15,(vlSelf->OTTER_Wrapper__DOT__clk_50));
    bufp->fullIData(oldp+16,(vlSelf->OTTER_Wrapper__DOT__IOBUS_out),32);
    bufp->fullIData(oldp+17,(vlSelf->OTTER_Wrapper__DOT__IOBUS_in),32);
    bufp->fullIData(oldp+18,(vlSelf->OTTER_Wrapper__DOT__IOBUS_addr),32);
    bufp->fullSData(oldp+19,(vlSelf->OTTER_Wrapper__DOT__r_lcdinstr),10);
    bufp->fullBit(oldp+20,(vlSelf->OTTER_Wrapper__DOT__r_lcd_ready));
    bufp->fullIData(oldp+21,(vlSelf->OTTER_Wrapper__DOT__r_random),32);
    bufp->fullBit(oldp+22,(vlSelf->OTTER_Wrapper__DOT__s_reset));
    bufp->fullBit(oldp+23,(vlSelf->OTTER_Wrapper__DOT__IOBUS_wr));
    bufp->fullBit(oldp+24,(vlSelf->OTTER_Wrapper__DOT__s_INTR));
    bufp->fullBit(oldp+25,(vlSelf->OTTER_Wrapper__DOT__r_vga_we));
    bufp->fullSData(oldp+26,(vlSelf->OTTER_Wrapper__DOT__r_vga_wa),13);
    bufp->fullCData(oldp+27,(vlSelf->OTTER_Wrapper__DOT__r_vga_wd),8);
    bufp->fullCData(oldp+28,(vlSelf->OTTER_Wrapper__DOT__r_vga_rd),8);
    bufp->fullSData(oldp+29,(vlSelf->OTTER_Wrapper__DOT__r_SSEG),16);
    bufp->fullBit(oldp+30,(vlSelf->OTTER_Wrapper__DOT__BTN_INTR));
    bufp->fullBit(oldp+31,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RST));
    bufp->fullBit(oldp+32,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__INTR));
    bufp->fullBit(oldp+33,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CLK));
    bufp->fullIData(oldp+34,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_IN),32);
    bufp->fullBit(oldp+35,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_WR));
    bufp->fullIData(oldp+36,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_OUT),32);
    bufp->fullIData(oldp+37,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IOBUS_ADDR),32);
    bufp->fullIData(oldp+38,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pc_bus),32);
    bufp->fullIData(oldp+39,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__npc_bus),32);
    bufp->fullIData(oldp+40,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rs1_bus),32);
    bufp->fullIData(oldp+41,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rs2_bus),32);
    bufp->fullIData(oldp+42,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_res_bus),32);
    bufp->fullIData(oldp+43,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__instr_bus),32);
    bufp->fullIData(oldp+44,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__itype_bus),32);
    bufp->fullIData(oldp+45,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__utype_bus),32);
    bufp->fullIData(oldp+46,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__stype_bus),32);
    bufp->fullIData(oldp+47,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jtype_bus),32);
    bufp->fullIData(oldp+48,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__btype_bus),32);
    bufp->fullIData(oldp+49,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__csr_RD),32);
    bufp->fullIData(oldp+50,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MTVEC),32);
    bufp->fullIData(oldp+51,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEPC),32);
    bufp->fullIData(oldp+52,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MSTATUS),32);
    bufp->fullBit(oldp+53,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__mret_exec));
    bufp->fullBit(oldp+54,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__int_taken));
    bufp->fullBit(oldp+55,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__csr_WE));
    bufp->fullIData(oldp+56,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__mem_data),32);
    bufp->fullIData(oldp+57,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jalr_baddr),32);
    bufp->fullIData(oldp+58,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__branch_baddr),32);
    bufp->fullIData(oldp+59,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__jal_baddr),32);
    bufp->fullBit(oldp+60,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_eq));
    bufp->fullBit(oldp+61,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_lt));
    bufp->fullBit(oldp+62,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__bcond_to_cu_ltu));
    bufp->fullIData(oldp+63,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rfwrmux_to_rf),32);
    bufp->fullIData(oldp+64,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__srcAmux_to_alu),32);
    bufp->fullIData(oldp+65,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__srcBmux_to_alu),32);
    bufp->fullIData(oldp+66,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pcmux_to_pc),32);
    bufp->fullBit(oldp+67,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PCWrite));
    bufp->fullBit(oldp+68,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__regWrite));
    bufp->fullBit(oldp+69,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memWE2));
    bufp->fullBit(oldp+70,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memRDEN1));
    bufp->fullBit(oldp+71,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__memRDEN2));
    bufp->fullBit(oldp+72,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__reset));
    bufp->fullCData(oldp+73,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_fun),4);
    bufp->fullCData(oldp+74,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_srcA),2);
    bufp->fullCData(oldp+75,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__alu_srcB),3);
    bufp->fullCData(oldp+76,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__pcSource),3);
    bufp->fullCData(oldp+77,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__rf_wr_sel),2);
    bufp->fullIData(oldp+78,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__srcA),32);
    bufp->fullIData(oldp+79,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__srcB),32);
    bufp->fullCData(oldp+80,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__ALU_FUN),4);
    bufp->fullIData(oldp+81,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU0__DOT__RESULT),32);
    bufp->fullIData(oldp+82,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__A),32);
    bufp->fullIData(oldp+83,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__B),32);
    bufp->fullIData(oldp+84,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__C),32);
    bufp->fullIData(oldp+85,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__D),32);
    bufp->fullCData(oldp+86,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__sel),2);
    bufp->fullIData(oldp+87,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCA_MUX__DOT__O),32);
    bufp->fullIData(oldp+88,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__A),32);
    bufp->fullIData(oldp+89,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__B),32);
    bufp->fullIData(oldp+90,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__C),32);
    bufp->fullIData(oldp+91,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__D),32);
    bufp->fullIData(oldp+92,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__E),32);
    bufp->fullIData(oldp+93,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__F),32);
    bufp->fullCData(oldp+94,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__sel),3);
    bufp->fullIData(oldp+95,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__ALU_SRCB_MUX__DOT__O),32);
    bufp->fullIData(oldp+96,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__J_TYPE),32);
    bufp->fullIData(oldp+97,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__B_TYPE),32);
    bufp->fullIData(oldp+98,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__PC),32);
    bufp->fullIData(oldp+99,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__I_TYPE),32);
    bufp->fullIData(oldp+100,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__RS1),32);
    bufp->fullIData(oldp+101,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__JAL),32);
    bufp->fullIData(oldp+102,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__BRANCH),32);
    bufp->fullIData(oldp+103,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BADDR_GEN0__DOT__JALR),32);
    bufp->fullIData(oldp+104,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__RS1),32);
    bufp->fullIData(oldp+105,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__RS2),32);
    bufp->fullBit(oldp+106,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_EQ));
    bufp->fullBit(oldp+107,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_LT));
    bufp->fullBit(oldp+108,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__BCOND_GEN0__DOT__BR_LTU));
    bufp->fullBit(oldp+109,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__clk));
    bufp->fullBit(oldp+110,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__RST));
    bufp->fullBit(oldp+111,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__mret_exec));
    bufp->fullBit(oldp+112,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__INT_TAKEN));
    bufp->fullSData(oldp+113,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__ADDR),12);
    bufp->fullBit(oldp+114,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__WR_EN));
    bufp->fullIData(oldp+115,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__PC),32);
    bufp->fullIData(oldp+116,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__WD),32);
    bufp->fullIData(oldp+117,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__RD),32);
    bufp->fullIData(oldp+118,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MSTATUS),32);
    bufp->fullIData(oldp+119,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MEPC),32);
    bufp->fullIData(oldp+120,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CSR0__DOT__MTVEC),32);
    bufp->fullCData(oldp+121,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__opcode),7);
    bufp->fullCData(oldp+122,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__funct3),3);
    bufp->fullBit(oldp+123,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__funct7));
    bufp->fullBit(oldp+124,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_eq));
    bufp->fullBit(oldp+125,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_lt));
    bufp->fullBit(oldp+126,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__br_ltu));
    bufp->fullBit(oldp+127,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__int_taken));
    bufp->fullCData(oldp+128,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_fun),4);
    bufp->fullCData(oldp+129,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_srcA),2);
    bufp->fullCData(oldp+130,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__alu_srcB),3);
    bufp->fullCData(oldp+131,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__pcSource),3);
    bufp->fullCData(oldp+132,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_DCDR0__DOT__rf_wr_sel),2);
    bufp->fullBit(oldp+133,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__clk));
    bufp->fullBit(oldp+134,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__RST));
    bufp->fullBit(oldp+135,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__INTR));
    bufp->fullCData(oldp+136,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__opcode),7);
    bufp->fullCData(oldp+137,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__funct3),3);
    bufp->fullBit(oldp+138,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__PCWrite));
    bufp->fullBit(oldp+139,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__regWrite));
    bufp->fullBit(oldp+140,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memWE2));
    bufp->fullBit(oldp+141,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memRDEN1));
    bufp->fullBit(oldp+142,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__memRDEN2));
    bufp->fullBit(oldp+143,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__reset));
    bufp->fullBit(oldp+144,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__csr_WE));
    bufp->fullBit(oldp+145,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__int_taken));
    bufp->fullBit(oldp+146,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__mret_exec));
    bufp->fullIData(oldp+147,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__NS),32);
    bufp->fullIData(oldp+148,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__CU_FSM0__DOT__PS),32);
    bufp->fullIData(oldp+149,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__INSTRUCT),32);
    bufp->fullIData(oldp+150,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__U_TYPE),32);
    bufp->fullIData(oldp+151,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__I_TYPE),32);
    bufp->fullIData(oldp+152,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__S_TYPE),32);
    bufp->fullIData(oldp+153,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__J_TYPE),32);
    bufp->fullIData(oldp+154,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__IMMED_GEN0__DOT__B_TYPE),32);
    bufp->fullBit(oldp+155,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_CLK));
    bufp->fullBit(oldp+156,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_RDEN1));
    bufp->fullBit(oldp+157,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_RDEN2));
    bufp->fullBit(oldp+158,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_WE2));
    bufp->fullSData(oldp+159,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_ADDR1),14);
    bufp->fullIData(oldp+160,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_ADDR2),32);
    bufp->fullIData(oldp+161,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DIN2),32);
    bufp->fullCData(oldp+162,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_SIZE),2);
    bufp->fullBit(oldp+163,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_SIGN));
    bufp->fullIData(oldp+164,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__IO_IN),32);
    bufp->fullBit(oldp+165,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__IO_WR));
    bufp->fullIData(oldp+166,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DOUT1),32);
    bufp->fullIData(oldp+167,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__MEM_DOUT2),32);
    bufp->fullSData(oldp+168,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__wordAddr2),14);
    bufp->fullIData(oldp+169,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__memReadWord),32);
    bufp->fullIData(oldp+170,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__ioBuffer),32);
    bufp->fullIData(oldp+171,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__memReadSized),32);
    bufp->fullCData(oldp+172,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__byteOffset),2);
    bufp->fullBit(oldp+173,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__MEM0__DOT__weAddrValid));
    bufp->fullBit(oldp+174,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_WRITE));
    bufp->fullBit(oldp+175,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_RST));
    bufp->fullIData(oldp+176,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_DIN),32);
    bufp->fullBit(oldp+177,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__CLK));
    bufp->fullIData(oldp+178,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC0__DOT__PC_COUNT),32);
    bufp->fullIData(oldp+179,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__A),32);
    bufp->fullIData(oldp+180,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__B),32);
    bufp->fullIData(oldp+181,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__C),32);
    bufp->fullIData(oldp+182,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__D),32);
    bufp->fullIData(oldp+183,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__E),32);
    bufp->fullIData(oldp+184,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__F),32);
    bufp->fullCData(oldp+185,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__sel),3);
    bufp->fullIData(oldp+186,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__PC_MUX__DOT__O),32);
    bufp->fullCData(oldp+187,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_ADR1),5);
    bufp->fullCData(oldp+188,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_ADR2),5);
    bufp->fullCData(oldp+189,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_WA),5);
    bufp->fullIData(oldp+190,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_WD),32);
    bufp->fullBit(oldp+191,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_EN));
    bufp->fullBit(oldp+192,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__CLK));
    bufp->fullIData(oldp+193,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_RS1),32);
    bufp->fullIData(oldp+194,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__RF_RS2),32);
    bufp->fullIData(oldp+195,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[0]),32);
    bufp->fullIData(oldp+196,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[1]),32);
    bufp->fullIData(oldp+197,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[2]),32);
    bufp->fullIData(oldp+198,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[3]),32);
    bufp->fullIData(oldp+199,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[4]),32);
    bufp->fullIData(oldp+200,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[5]),32);
    bufp->fullIData(oldp+201,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[6]),32);
    bufp->fullIData(oldp+202,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[7]),32);
    bufp->fullIData(oldp+203,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[8]),32);
    bufp->fullIData(oldp+204,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[9]),32);
    bufp->fullIData(oldp+205,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[10]),32);
    bufp->fullIData(oldp+206,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[11]),32);
    bufp->fullIData(oldp+207,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[12]),32);
    bufp->fullIData(oldp+208,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[13]),32);
    bufp->fullIData(oldp+209,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[14]),32);
    bufp->fullIData(oldp+210,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[15]),32);
    bufp->fullIData(oldp+211,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[16]),32);
    bufp->fullIData(oldp+212,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[17]),32);
    bufp->fullIData(oldp+213,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[18]),32);
    bufp->fullIData(oldp+214,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[19]),32);
    bufp->fullIData(oldp+215,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[20]),32);
    bufp->fullIData(oldp+216,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[21]),32);
    bufp->fullIData(oldp+217,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[22]),32);
    bufp->fullIData(oldp+218,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[23]),32);
    bufp->fullIData(oldp+219,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[24]),32);
    bufp->fullIData(oldp+220,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[25]),32);
    bufp->fullIData(oldp+221,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[26]),32);
    bufp->fullIData(oldp+222,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[27]),32);
    bufp->fullIData(oldp+223,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[28]),32);
    bufp->fullIData(oldp+224,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[29]),32);
    bufp->fullIData(oldp+225,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[30]),32);
    bufp->fullIData(oldp+226,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF0__DOT__ram[31]),32);
    bufp->fullIData(oldp+227,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__A),32);
    bufp->fullIData(oldp+228,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__B),32);
    bufp->fullIData(oldp+229,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__C),32);
    bufp->fullIData(oldp+230,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__D),32);
    bufp->fullCData(oldp+231,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__sel),2);
    bufp->fullIData(oldp+232,(vlSelf->OTTER_Wrapper__DOT__CPU__DOT__RF_WR_MUX__DOT__O),32);
    bufp->fullBit(oldp+233,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__CLK));
    bufp->fullBit(oldp+234,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__BTN));
    bufp->fullBit(oldp+235,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__DB_BTN));
    bufp->fullCData(oldp+236,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_LOW_GOING_HIGH_CLOCKS),8);
    bufp->fullCData(oldp+237,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_HIGH_GOING_LOW_CLOCKS),8);
    bufp->fullCData(oldp+238,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__c_ONE_SHOT_CLOCKS),8);
    bufp->fullIData(oldp+239,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__NS),32);
    bufp->fullIData(oldp+240,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__PS),32);
    bufp->fullCData(oldp+241,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_db_count),8);
    bufp->fullBit(oldp+242,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_count_rst));
    bufp->fullBit(oldp+243,(vlSelf->OTTER_Wrapper__DOT__DEBOUCE__DOT__s_count_inc));
    bufp->fullBit(oldp+244,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CLK));
    bufp->fullBit(oldp+245,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__MODE));
    bufp->fullSData(oldp+246,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__DATA_IN),16);
    bufp->fullCData(oldp+247,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CATHODES),8);
    bufp->fullCData(oldp+248,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__ANODES),4);
    bufp->fullSData(oldp+249,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCD_Val),16);
    bufp->fullSData(oldp+250,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__Hex_Val),16);
    bufp->fullSData(oldp+251,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__HEX),16);
    bufp->fullCData(oldp+252,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__THOUSANDS),4);
    bufp->fullCData(oldp+253,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__HUNDREDS),4);
    bufp->fullCData(oldp+254,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__TENS),4);
    bufp->fullCData(oldp+255,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__ONES),4);
    bufp->fullIData(oldp+256,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__BCDMod__DOT__i),32);
    bufp->fullBit(oldp+257,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__CLK));
    bufp->fullSData(oldp+258,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__HEX),16);
    bufp->fullCData(oldp+259,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__CATHODES),8);
    bufp->fullCData(oldp+260,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__ANODES),4);
    bufp->fullBit(oldp+261,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__s_clk_500));
    bufp->fullCData(oldp+262,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__r_disp_digit),2);
    bufp->fullIData(oldp+263,(vlSelf->OTTER_Wrapper__DOT__SSG_DISP__DOT__CathMod__DOT__clk_div_counter),20);
}
